let imgSymbol = {
    btc : "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/256/Bitcoin-BTC-icon.png",
    eos : "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/256/EOS-icon.png",
    miota: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency/512/IOTA-icon.png",
    eth: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Ethereum-ETH-icon.png",
    xrp: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Ripple-XRP-icon.png",
    bch: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Bitcoin-Cash-BCH-icon.png",
    ltc: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Litecoin-LTC-icon.png",
    ada: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/Cardano-ADA-icon.png",
    xlm: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/Stellar-XLM-icon.png", 
    trx: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/TRON-TRX-icon.png",
    neo: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/NEO-icon.png",
    dash: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Dash-icon.png",
    xmr: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Monero-XMR-icon.png",
    xem: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/NEM-XEM-icon.png",
    ven: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/VeChain-VEN-icon.png",
    usdt: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Tether-USDT-icon.png",
    bcn: "http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/128/Bytecoin-BCN-icon.png",
    etc: "",
    icx: "",
    qtum: "",
    bnb: "",
    omg: "",
    lsk: "",
    zil: "",
    btg: "",
    ae: "",
    ont: "",
    xvg: "",
    nano: "",
    zrx: "",
    steem: "",
    sc: "",
    dcr: "",
    wan: "",
    bts: "",
    btm: "",
    waves: "",
    bcd: "",
    strat: "",
    ppt: "",
    rhoc: "",
    mkr: "",
    rep: "",
    doge: "",
    btcp: "",
    gnt: "",
    iost: "",
    snt: "",
    hsr: "",
    lrc: "",
    bat: ""
}

module.exports = imgSymbol;